--CREATE TABLE
USE mutants

CREATE TABLE `Dnas` (
  `id_dna` int(11) NOT NULL AUTO_INCREMENT,
  `dna` tinyblob,
  `es_mutante` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id_dna`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

--ROLLBACK
DROP TABLE IF EXISTS `Dnas`